Add MAINTAINERS.adoc
Vandit1604/jenkins-docs pull request #103
Opened 2023-12-27 13:22 UTC by Vandit1604

Add the guide to versioning the documentation. Currently named it `MAINTAINERS.adoc` it can be changed though.

2023-12-28 02:24 UTC, krisstern requested changes

2023-12-28 02:24 UTC, krisstern commented on MAINTAINERS.adoc
> +- Begin by creating a dedicated branch for a new release, following semantic versioning, for example, _2.426.1_.
```suggestion
- Begin by creating a dedicated branch for a new release, following semantic versioning, for example, _2.426.x_.
```

2023-12-28 02:24 UTC, krisstern commented on MAINTAINERS.adoc
> +- Add the newly created branch, such as _**2.426.1**_, into the `antora-playbook.yml` file located in the playbook directory. This inclusion instructs Antora to fetch this branch and generate documen
```suggestion
- Add the newly created branch, such as _**2.426.x**_, into the `antora-playbook.yml` file located in the playbook directory. This inclusion instructs Antora to fetch this branch and generate documentation for it, aligned with the version specified in the `antora.yml` file.
```

2023-12-28 02:24 UTC, krisstern commented on MAINTAINERS.adoc
> +- The `content.sources.branches` key should be updated with the name of the newly created _**2.426.1**_ branch
```suggestion
- The `content.sources.branches` key should be updated with the name of the newly created _**2.426.x**_ branch
```

2023-12-28 11:19 UTC, krisstern requested changes

2023-12-28 11:19 UTC, krisstern commented on MAINTAINERS.adoc
> +- This branch should be created 2 weeks prior the minor release when the release candidate is released.
```suggestion
```

2023-12-28 11:19 UTC, krisstern commented on MAINTAINERS.adoc
> +NOTE: The main branch will contain documentation for the next release and when a release candidate will be released and another branch is created from the `main` branch. In simple terms, The `main` b
```suggestion
NOTE: The main branch will contain documentation for the next release and when a release candidate will be released and another branch is created from the `main` branch. In simple terms, The `main` branch will always contains documentation for the next release and some time before the release, we will create a versioned branch. 
```

2023-12-28 11:40 UTC, Vandit1604 commented
@krisstern I have added all the necessary information need to start versioning the documentation. Is there any question that jumps at you that should be addressed in the file. If not we can merge this.

2023-12-29 05:51 UTC, krisstern approved these changes

2023-12-29 05:52 UTC, merged